import { motion } from "framer-motion";
import { BellRing, CheckCheck, Download, Search } from "lucide-react";
import { useMemo, useState } from "react";

import { PageHeader } from "@/components/PageHeader";
import { SeverityBadge } from "@/components/SeverityBadge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { dateTimeStr } from "@/lib/format";
import { buildPdf, downloadPdf } from "@/lib/pdf";
import {
  simulation,
  useAlerts,
  type Severity,
} from "@/lib/simulation";
import { cn } from "@/lib/utils";

const FILTERS: Array<{ id: Severity | "all"; label: string }> = [
  { id: "all", label: "All" },
  { id: "critical", label: "Critical" },
  { id: "warning", label: "Warning" },
  { id: "info", label: "Info" },
  { id: "ok", label: "Normal" },
];

export default function Alerts() {
  const alerts = useAlerts();
  const [filter, setFilter] = useState<Severity | "all">("all");
  const [q, setQ] = useState("");

  const counts = useMemo(() => {
    const c: Record<string, number> = { all: alerts.length };
    for (const a of alerts) c[a.severity] = (c[a.severity] ?? 0) + 1;
    return c;
  }, [alerts]);

  const filtered = alerts.filter((a) => {
    if (filter !== "all" && a.severity !== filter) return false;
    if (q.trim()) {
      const s = q.toLowerCase();
      if (!(a.title + a.detail + a.source).toLowerCase().includes(s)) return false;
    }
    return true;
  });

  const exportReport = () => {
    const sections = alerts.slice(0, 60).map((a) => ({
      heading: `${a.title.toUpperCase()}`,
      lines: [
        { text: `${dateTimeStr(a.ts)}  ·  Severity: ${a.severity.toUpperCase()}  ·  Source: ${a.source}` },
        { text: a.detail },
        ...(a.recommendation ? [{ text: `Action: ${a.recommendation}` }] : []),
        { text: " " },
      ],
    }));
    const pdf = buildPdf(
      "PumpGuardian AI — Alert Report",
      `Asset CHW-02 · Generated ${dateTimeStr(Date.now())} · ${alerts.length} alerts`,
      sections.length ? sections : [{ heading: "NO ALERTS", lines: [{ text: "Alert log is empty." }] }],
    );
    downloadPdf(`pumpguardian-alert-report-${Date.now()}.pdf`, pdf);
  };

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Alert Center"
        description="Alarm events generated by the threshold engine and the AI model — updates live as the simulation evolves."
        actions={
          <>
            <Button variant="outline" size="sm" onClick={() => simulation.markAllAlertsRead()}>
              <CheckCheck className="size-3.5" /> Mark all read
            </Button>
            <Button variant="outline" size="sm" onClick={exportReport}>
              <Download className="size-3.5" /> Export PDF
            </Button>
          </>
        }
      />

      <div className="flex flex-col gap-4">
        {/* summary strip */}
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">
          {FILTERS.map((f) => (
            <button
              key={f.id}
              onClick={() => setFilter(f.id)}
              className={cn(
                "glass flex items-center justify-between rounded-xl px-4 py-3 transition-all duration-200 hover:border-white/20",
                filter === f.id && "border-primary/50 bg-primary/10",
              )}
            >
              <span className="text-[12px] font-medium text-muted-foreground">{f.label}</span>
              <span className={cn("numeric text-[15px] font-semibold", f.id === "critical" ? "text-red-500" : f.id === "warning" ? "text-orange-500" : f.id === "ok" ? "text-green-500" : "text-foreground")}>
                {counts[f.id] ?? 0}
              </span>
            </button>
          ))}
        </div>

        {/* search */}
        <div className="relative max-w-sm">
          <Search className="absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground" />
          <Input
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder="Search alerts…"
            className="pl-9"
          />
        </div>

        {/* alert cards */}
        <div className="flex flex-col gap-3">
          {filtered.length === 0 && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="glass flex flex-col items-center gap-3 rounded-xl p-12 text-center"
            >
              <BellRing className="size-8 text-muted-foreground/60" />
              <p className="text-sm font-medium text-foreground">No alerts match</p>
              <p className="max-w-sm text-[12.5px] text-muted-foreground">
                {q || filter !== "all"
                  ? "Try clearing the search or severity filter."
                  : "The threshold engine has not raised any alarms. Run a fault scenario from the Simulation panel to generate alerts."}
              </p>
            </motion.div>
          )}

          {filtered.map((a, i) => (
            <motion.div
              key={a.id}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: Math.min(i * 0.04, 0.4), duration: 0.3 }}
              className={cn(
                "glass flex flex-col gap-3 rounded-xl p-4 transition-colors duration-300 hover:border-white/20 sm:flex-row sm:items-start",
                a.severity === "critical" && "border-red-500/25 bg-red-500/5",
                a.severity === "warning" && "border-orange-500/20",
                !a.read && "border-primary/30",
              )}
            >
              <div className="flex w-full items-start justify-between gap-3 sm:w-40 sm:flex-col sm:justify-start">
                <SeverityBadge severity={a.severity} />
                <span className="numeric text-[11px] text-muted-foreground">{dateTimeStr(a.ts)}</span>
                {!a.read && (
                  <span className="ml-auto rounded-full bg-primary/15 px-2 py-0.5 text-[10px] font-semibold text-primary sm:ml-0">
                    NEW
                  </span>
                )}
              </div>
              <div className="min-w-0 flex-1">
                <p className={cn("text-[14px]", a.read ? "font-medium text-muted-foreground" : "font-semibold text-foreground")}>
                  {a.title}
                </p>
                <p className="mt-1 text-[12.5px] leading-relaxed text-muted-foreground">{a.detail}</p>
                {a.recommendation && (
                  <p className="mt-2 rounded-md border border-border/50 bg-muted/30 px-3 py-1.5 text-[12px] text-foreground">
                    <span className="font-semibold text-primary">Recommended:</span> {a.recommendation}
                  </p>
                )}
                <p className="mt-2 text-[11px] uppercase tracking-wider text-muted-foreground">{a.source}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
}
